# Generated by Django 5.2.5 on 2025-11-05 14:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='Anonymized patient identifier (e.g., PT001)', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be in format: 555-555-5555', regex='^\\d{3}-\\d{3}-\\d{4}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('exam_type', models.CharField(choices=[('MRI_BRAIN', 'MRI Brain'), ('MRI_SPINE', 'MRI Spine'), ('MRI_KNEE', 'MRI Knee'), ('MRI_SHOULDER', 'MRI Shoulder'), ('MRI_ABDOMEN', 'MRI Abdomen'), ('CT_HEAD', 'CT Head'), ('CT_CHEST', 'CT Chest'), ('CT_ABDOMEN', 'CT Abdomen'), ('XRAY_CHEST', 'X-Ray Chest'), ('XRAY_SPINE', 'X-Ray Spine'), ('ULTRASOUND', 'Ultrasound')], max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('CHECKED_IN', 'Checked In'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('referring_physician', models.CharField(max_length=100)),
                ('clinical_indication', models.TextField(blank=True, help_text="Reason for exam (e.g., 'r/o rotator cuff tear')")),
                ('special_instructions', models.TextField(blank=True, help_text='Special prep or patient needs')),
                ('duration_minutes', models.IntegerField(default=30, help_text='Expected appointment duration')),
                ('room_number', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.patient')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'ordering': ['appointment_date'],
            },
        ),
    ]
